# Generated by Django 2.2.7 on 2019-11-23 07:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('irekua_database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visualizer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='created_on', help_text='Date of creation', verbose_name='created on')),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on')),
                ('name', models.CharField(db_column='name', help_text='Name of visualizer app', max_length=64, verbose_name='name')),
                ('version', models.CharField(db_column='version', help_text='Version of visualizer app', max_length=16, verbose_name='version')),
                ('javascript_file', models.FileField(db_column='javascript_file', help_text='Javascript file containing visualizer component', upload_to='visualizers/', verbose_name='javascript file')),
                ('repository', models.URLField(blank=True, db_column='repository', help_text='Link to app repository', verbose_name='repository')),
            ],
            options={
                'verbose_name': 'Visualizer',
                'verbose_name_plural': 'Visualizers',
                'ordering': ['-created_on'],
            },
        ),
        migrations.CreateModel(
            name='VisualizerItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='is_active', default=True, help_text='Is visualizer app active?', verbose_name='is active')),
                ('item_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='irekua_database.ItemType')),
                ('visualizer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='selia_visualizers.Visualizer')),
            ],
            options={
                'verbose_name': 'VisualizerItemType',
                'verbose_name_plural': 'VisualizerItemTypes',
                'unique_together': {('item_type', 'visualizer')},
            },
        ),
        migrations.AddField(
            model_name='visualizer',
            name='item_types',
            field=models.ManyToManyField(through='selia_visualizers.VisualizerItemType', to='irekua_database.ItemType'),
        ),
        migrations.AlterUniqueTogether(
            name='visualizer',
            unique_together={('name', 'version')},
        ),
    ]
