# Generated by Django 3.1.1 on 2020-09-25 21:46

from django.db import migrations, models
import django.db.models.deletion
import irekua_database.utils


class Migration(migrations.Migration):

    dependencies = [
        ('selia_visualizers', '0001_initial'),
        ('irekua_database', '0007_delete_visualizer'),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[
                migrations.CreateModel(
                    name='Visualizer',
                    fields=[
                        ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                        ('created_on', models.DateTimeField(auto_now_add=True, db_column='created_on', help_text='Date of creation', verbose_name='created on')),
                        ('modified_on', models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on')),
                        ('name', models.CharField(db_column='name', help_text='Name of visualizer app', max_length=64, verbose_name='name')),
                        ('version', models.CharField(db_column='version', help_text='Version of visualizer app', max_length=16, verbose_name='version')),
                        ('website', models.URLField(blank=True, db_column='website', help_text='Link to visualizer website', verbose_name='website')),
                        ('configuration_schema', models.JSONField(blank=True, db_column='configuration_schema', default=irekua_database.utils.simple_JSON_schema, help_text='JSON schema for annotation tool configuration info', validators=[irekua_database.utils.validate_JSON_schema], verbose_name='configuration schema')),
                    ],
                    options={
                        'verbose_name': 'Visualizer',
                        'verbose_name_plural': 'Visualizers',
                        'ordering': ['-created_on'],
                        'unique_together': {('name', 'version')},
                    },
                ),
                migrations.AlterField(
                    model_name='visualizercomponent',
                    name='visualizer',
                    field=models.OneToOneField(db_column='visualizer_id', help_text='Visualizer', on_delete=django.db.models.deletion.CASCADE, to='selia_visualizers.visualizer', verbose_name='visualizer'),
                ),
            ],
            database_operations=[],
        )
    ]
