# Generated by Django 3.1.1 on 2020-09-26 00:20

from django.db import migrations, models
import django.db.models.deletion
import irekua_database.utils


def break_visualizers_into_versions(apps, schema_editor):
    Visualizer = apps.get_model('selia_visualizers', 'Visualizer')
    VisualizerVersion = apps.get_model('selia_visualizers', 'VisualizerVersion')

    visualizers = Visualizer.objects.all().order_by('name').distinct('name').values('name')

    for visualizer in visualizers:
        name = visualizer['name']

        queryset = Visualizer.objects.filter(name=name).order_by('version')
        first_version = queryset.first()
        for version in queryset:
            VisualizerVersion.objects.create(
                visualizer=first_version,
                version=version.version,
                configuration_schema=version.configuration_schema
            )

    assert Visualizer.objects.all().count() == VisualizerVersion.objects.all().count()


class Migration(migrations.Migration):

    dependencies = [
        ('selia_visualizers', '0002_auto_20200925_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualizerVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True, db_column='created_on', help_text='Date of creation', verbose_name='created on')),
                ('modified_on', models.DateTimeField(auto_now=True, db_column='modified_on', help_text='Date of last modification', verbose_name='modified on')),
                ('version', models.CharField(db_column='version', help_text='Version of visualizer app', max_length=16, verbose_name='version')),
                ('configuration_schema', models.JSONField(blank=True, db_column='configuration_schema', default=irekua_database.utils.simple_JSON_schema, help_text='JSON schema for visualizer tool configuration info', validators=[irekua_database.utils.validate_JSON_schema], verbose_name='configuration schema')),
                ('visualizer', models.ForeignKey(db_column='visualizer_id', help_text='Visualizer', on_delete=django.db.models.deletion.CASCADE, to='selia_visualizers.visualizer', verbose_name='visualizer')),
            ],
            options={
                'verbose_name': 'Visualizer Version',
                'verbose_name_plural': 'Visualizer Versions',
                'ordering': ['visualizer', '-version'],
                'unique_together': {('visualizer', 'version')},
            },
        ),
        migrations.AddField(
            model_name='visualizer',
            name='description',
            field=models.TextField(blank=True, db_column='description', help_text='Description of the visualizer', verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='visualizer',
            name='configuration_schema',
            field=models.JSONField(blank=True, db_column='configuration_schema', default=irekua_database.utils.simple_JSON_schema, help_text='JSON schema for visualizer tool configuration info', validators=[irekua_database.utils.validate_JSON_schema], verbose_name='configuration schema'),
        ),
        migrations.AlterUniqueTogether(
            name='visualizer',
            unique_together=set(),
        ),
        migrations.RunPython(
            break_visualizers_into_versions,
        ),
    ]
