# Generated by Django 3.1.1 on 2020-09-26 01:14

from django.db import migrations, models
import django.db.models.deletion
import selia_visualizers.models.visualizer_module


def copy_visualization_components_into_module_structure(apps, schema_editor):
    VisualizerComponent = apps.get_model('selia_visualizers', 'VisualizerComponent')
    VisualizerVersion = apps.get_model('selia_visualizers', 'VisualizerVersion')
    VisualizerModule = apps.get_model('selia_visualizers', 'VisualizerModule')
    VisualizerModuleItemType = apps.get_model('selia_visualizers', 'VisualizerModuleItemType')
    VisualizerComponentItemType = apps.get_model('selia_visualizers', 'VisualizerComponentItemType')

    pre_migration_versions = VisualizerVersion.objects.all().count()

    for component in VisualizerComponent.objects.all():
        visualizer_version = VisualizerVersion.objects.get(
            visualizer__name=component.visualizer.name,
            version=component.visualizer.version)

        visualizer_module = VisualizerModule(
            visualizerversion_ptr=visualizer_version,
            javascript_file=component.javascript_file)

        visualizer_module.__dict__.update(visualizer_version.__dict__)
        visualizer_module.save()

        assert component.visualizer.name == visualizer_module.visualizer.name
        assert component.visualizer.version == visualizer_module.version

        for relation in VisualizerComponentItemType.objects.filter(visualizer_component=component):
            VisualizerModuleItemType(
                visualizer_module=visualizer_module,
                item_type=relation.item_type,
                is_active=relation.is_active
            ).save()

        assert component.item_types.all().count() == visualizer_module.item_types.all().count()

    assert VisualizerVersion.objects.all().count() == pre_migration_versions


class Migration(migrations.Migration):

    dependencies = [
        ('irekua_database', '0007_delete_visualizer'),
        ('selia_visualizers', '0003_auto_20200925_1920'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualizerModule',
            fields=[
                ('visualizerversion_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='selia_visualizers.visualizerversion')),
                ('javascript_file', models.FileField(db_column='javascript_file', help_text='Javascript file containing visualizer version module', upload_to=selia_visualizers.models.visualizer_module.visualizer_version_module_path, verbose_name='javascript file')),
            ],
            options={
                'verbose_name': 'Visualizer Version Module',
                'verbose_name_plural': 'Visualizers Version Modules',
            },
            bases=('selia_visualizers.visualizerversion',),
        ),
        migrations.CreateModel(
            name='VisualizerModuleItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='is_active', default=True, help_text='Is visualizer app active?', verbose_name='is active')),
                ('item_type', models.ForeignKey(db_column='item_type_id', help_text='Item type', on_delete=django.db.models.deletion.CASCADE, to='irekua_database.itemtype', verbose_name='item type')),
                ('visualizer_module', models.ForeignKey(db_column='visualizer_module_id', help_text='Visualizer module', on_delete=django.db.models.deletion.CASCADE, to='selia_visualizers.visualizermodule', verbose_name='visualizer module')),
            ],
            options={
                'verbose_name': 'Visualizer Module Item Type',
                'verbose_name_plural': 'Visualizer Module Item Types',
                'unique_together': {('item_type', 'visualizer_module')},
            },
        ),
        migrations.AddField(
            model_name='visualizermodule',
            name='item_types',
            field=models.ManyToManyField(through='selia_visualizers.VisualizerModuleItemType', to='irekua_database.ItemType'),
        ),
        migrations.RunPython(
            copy_visualization_components_into_module_structure,
        ),
    ]
