# Generated by Django 3.1.1 on 2020-09-26 01:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('selia_visualizers', '0004_auto_20200925_2014'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='visualizercomponentitemtype',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='visualizercomponentitemtype',
            name='item_type',
        ),
        migrations.RemoveField(
            model_name='visualizercomponentitemtype',
            name='visualizer_component',
        ),
        migrations.RemoveField(
            model_name='visualizer',
            name='version',
        ),
        migrations.DeleteModel(
            name='VisualizerComponent',
        ),
        migrations.DeleteModel(
            name='VisualizerComponentItemType',
        ),
    ]
