# Generated by Django 3.1.1 on 2020-09-30 04:42
from django.db import models
from django.db import migrations


def remove_hanging_visualizers(apps, schema_editor):
    Visualizer = apps.get_model('selia_visualizers', 'Visualizer')
    (Visualizer.objects.all()
        .annotate(versions=models.Count('visualizerversion'))
        .filter(versions=0)
        .delete())


class Migration(migrations.Migration):

    dependencies = [
        ('selia_visualizers', '0005_auto_20200925_2038'),
    ]

    operations = [
        migrations.RunPython(
            remove_hanging_visualizers,
            atomic=True,
        ),
    ]
