# Generated by Django 3.1.1 on 2020-09-30 06:04

from django.db import migrations, models
import django.db.models.deletion


def move_item_type_relations_to_visualizers(apps, schema_editor):
    VisualizerItemType = apps.get_model('selia_visualizers', 'VisualizerItemType')
    VisualizerModuleItemType = apps.get_model('selia_visualizers', 'VisualizerModuleItemType')

    for rel in VisualizerModuleItemType.objects.all():
        vis_item_type, _ = VisualizerItemType.objects.get_or_create(
            visualizer=rel.visualizer_module.visualizer,
            item_type=rel.item_type,
            defaults=dict(is_active=False))

        # Make default visualizer for item type if a version of the visualizer
        # was previously activated.
        if rel.is_active:
            vis_item_type.is_active = True
            vis_item_type.save()

        # Make the default version of the visualizer if the module was activated.
        rel.visualizer_module.is_active = rel.is_active
        rel.save()


class Migration(migrations.Migration):

    dependencies = [
        ('irekua_database', '0007_delete_visualizer'),
        ('selia_visualizers', '0006_auto_20200929_2342'),
    ]

    operations = [
        migrations.CreateModel(
            name='VisualizerItemType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(db_column='is_active', default=True, help_text='Indicates wheter this visualizer should be used as the default visualizer of this item type.', verbose_name='is active')),
                ('item_type', models.ForeignKey(db_column='item_type_id', help_text='Item type', on_delete=django.db.models.deletion.CASCADE, to='irekua_database.itemtype', verbose_name='item type')),
                ('visualizer', models.ForeignKey(db_column='visualizer_id', help_text='Visualizer', on_delete=django.db.models.deletion.CASCADE, to='selia_visualizers.visualizer', verbose_name='visualizer')),
            ],
            options={
                'verbose_name': 'Visualizer Item Type',
                'verbose_name_plural': 'Visualizer Item Types',
                'unique_together': {('item_type', 'visualizer')},
            },
        ),
        migrations.AddField(
            model_name='visualizermodule',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True, help_text='Boolean flag that indicates whether this version is to be used as the default version of this visualizer.', verbose_name='is active'),
        ),
        migrations.AddField(
            model_name='visualizer',
            name='item_types',
            field=models.ManyToManyField(through='selia_visualizers.VisualizerItemType', to='irekua_database.ItemType'),
        ),
        migrations.RunPython(
            move_item_type_relations_to_visualizers,
            atomic=True,
        ),
        migrations.RemoveField(
            model_name='visualizermodule',
            name='item_types',
        ),
        migrations.DeleteModel(
            name='VisualizerModuleItemType',
        ),
    ]
